# Optional signing for build outputs. Each mechanism here only
# activates when its credential is present as an environment
# variable -- unconfigured is the expected, normal state for a local
# developer build, not an error, so every function degrades to a
# clear skip message on stderr rather than failing the build. None
# of these credentials can be generated by the build itself: a GPG
# keypair, a Windows Authenticode certificate, and an Apple Developer
# ID are all things a human obtains and supplies (the latter two
# specifically require a paid CA purchase or Apple Developer Program
# enrollment) via CI secrets or local environment variables, under
# the names used below. Meant to be sourced by each build script
# after PROJECT_ROOT is set; none of these need it directly, but
# living alongside app_metadata.sh/project_metadata.sh keeps every
# piece of cross-script shared config in one place.

# GPG: a detached, armored signature (<file>.asc) alongside the file
# itself -- the standard way a project distributes a verifiable
# release artifact without needing a full APT/package repository of
# its own. Verified with: gpg --verify <file>.asc <file>
#   SIT_GPG_KEY_ID     -- signing key's id/fingerprint/email; unset skips
#   SIT_GPG_PASSPHRASE -- only if that key needs one
sign_file_gpg() {
    local target="$1"
    if [ -z "${SIT_GPG_KEY_ID:-}" ]; then
        echo "Signing: SIT_GPG_KEY_ID not set -- skipping GPG signature for $(basename "$target")." >&2
        return 0
    fi
    if ! command -v gpg >/dev/null 2>&1; then
        echo "Warning: SIT_GPG_KEY_ID is set but gpg isn't installed -- skipping signature for $(basename "$target")." >&2
        return 0
    fi
    rm -f "$target.asc"
    if [ -n "${SIT_GPG_PASSPHRASE:-}" ]; then
        printf '%s' "$SIT_GPG_PASSPHRASE" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 \
            --local-user "$SIT_GPG_KEY_ID" --detach-sign --armor --output "$target.asc" "$target"
    else
        gpg --batch --yes --local-user "$SIT_GPG_KEY_ID" --detach-sign --armor --output "$target.asc" "$target"
    fi
    echo "Signed: $(basename "$target.asc")"
}

# Windows Authenticode via signtool.exe, part of the Windows SDK and
# present on GitHub's windows-latest runners -- this build already
# runs natively on Windows under MSYS2, so signtool is the natural
# fit here rather than a Linux cross-signing tool.
#   SIT_WINDOWS_CERT_PATH     -- a .pfx/.p12 certificate file; unset skips
#   SIT_WINDOWS_CERT_PASSWORD -- that certificate's password
sign_file_authenticode() {
    local target="$1"
    if [ -z "${SIT_WINDOWS_CERT_PATH:-}" ]; then
        echo "Signing: SIT_WINDOWS_CERT_PATH not set -- skipping Authenticode signature for $(basename "$target")." >&2
        return 0
    fi
    local signtool
    signtool="$(command -v signtool.exe || command -v signtool || true)"
    if [ -z "$signtool" ]; then
        echo "Warning: SIT_WINDOWS_CERT_PATH is set but signtool(.exe) wasn't found on PATH -- skipping signature for $(basename "$target")." >&2
        return 0
    fi
    "$signtool" sign /f "$SIT_WINDOWS_CERT_PATH" /p "$SIT_WINDOWS_CERT_PASSWORD" \
        /fd sha256 /tr http://timestamp.digicert.com /td sha256 "$target"
    echo "Signed: $(basename "$target")"
}

# macOS Developer ID codesigning, plus optional notarization. This
# replaces the ad-hoc signature (`codesign --sign -`) build_macos.sh
# otherwise applies to individual dylibs -- ad-hoc signing is only
# enough to keep install_name_tool's own edits from leaving a dylib
# with an invalid signature, not something Gatekeeper trusts; signing
# the whole bundle under a real identity here re-signs everything,
# dylibs included, superseding the ad-hoc ones.
#   SIT_MACOS_SIGN_IDENTITY       -- the "Developer ID Application: ..."
#                                    identity string from `security
#                                    find-identity -v -p codesigning`;
#                                    unset skips signing entirely
#   SIT_MACOS_NOTARIZE_APPLE_ID   -- notarization additionally needs all
#   SIT_MACOS_NOTARIZE_PASSWORD      three of these; an app-specific
#   SIT_MACOS_NOTARIZE_TEAM_ID       password, not the Apple ID's own
sign_app_macos() {
    local app_dir="$1"
    if [ -z "${SIT_MACOS_SIGN_IDENTITY:-}" ]; then
        echo "Signing: SIT_MACOS_SIGN_IDENTITY not set -- shipping ad-hoc signed only (Gatekeeper will still warn; first launch needs right-click > Open)." >&2
        return 0
    fi
    codesign --deep --force --options runtime --timestamp \
        --sign "$SIT_MACOS_SIGN_IDENTITY" "$app_dir"
    echo "Signed: $(basename "$app_dir") with $SIT_MACOS_SIGN_IDENTITY"

    if [ -n "${SIT_MACOS_NOTARIZE_APPLE_ID:-}" ] && [ -n "${SIT_MACOS_NOTARIZE_PASSWORD:-}" ] && [ -n "${SIT_MACOS_NOTARIZE_TEAM_ID:-}" ]; then
        local zip_for_notarize
        zip_for_notarize="$(dirname "$app_dir")/$(basename "$app_dir" .app)-notarize.zip"
        ditto -c -k --keepParent "$app_dir" "$zip_for_notarize"
        xcrun notarytool submit "$zip_for_notarize" \
            --apple-id "$SIT_MACOS_NOTARIZE_APPLE_ID" \
            --password "$SIT_MACOS_NOTARIZE_PASSWORD" \
            --team-id "$SIT_MACOS_NOTARIZE_TEAM_ID" \
            --wait
        xcrun stapler staple "$app_dir"
        rm -f "$zip_for_notarize"
        echo "Notarized and stapled: $(basename "$app_dir")"
    else
        echo "Signing: notarization env vars not fully set -- signed but not notarized (Gatekeeper will still warn on first launch without notarization)." >&2
    fi
}
